FROM java:8

RUN mkdir /jmeter \
    && cd /jmeter/ \
    && wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.2.tgz \
    && tar -xvzf apache-jmeter-5.2.tgz \
    && rm apache-jmeter-5.2.tgz

ENV JMETER_HOME /jmeter/apache-jmeter-5.2/

# Add Jmeter to the Path
ENV PATH $JMETER_HOME/bin:$PATH
